Repository webliumteam/blocks, pull requests merged in 2018-03, with the labels that each got.

#559 add additional text
  .DS_Store
  assets/.DS_Store
  src/.DS_Store
  src/component.js
  src/style.css
Labels: reject

#622 [About-W1]: hotfix for additional button
  .gitignore
  src/component.js
Labels: wontfix

#625 [Cover-W2]: fix arrows bug in editor
  src/style.css
Labels: wontfix

#630 add caption decorator and doc
  README.md
  package.json
  src/component.js
  src/style.css
Labels: enhancement

#631 W/series 2/about/options
  README.md
  src/component.js
  src/style.css
Labels: enhancement

#632 upd readme
  README.md
Labels: enhancement

#633 add caption decorator and doc
  README.md
  src/component.js
  src/style.css
Labels: enhancement

#635 add caption decorator and doc
  README.md
  src/component.js
  src/style.css
Labels: enhancement

#636 add caption decorator and doc
  README.md
  src/component.js
  src/style.css
Labels: enhancement

#637 add caption decorator and doc
  README.md
  src/component.js
  src/style.css
Labels: enhancement

#660 [CoverW3]: fixed description
  package.json
  src/component.js
  src/style.css
Labels: wontfix

#661 [ContactsW3]: finished first iteration
  block.https.weblium.co
  package.json
  src/component.js
  src/style.css
Labels: good first issue

#662 [HeaderW1]: fix expanded menu bg
  block.http.weblium
  package.json
  src/style.css
Labels: wontfix

#665 hotfix section paddings
  src/style.css
Labels: wontfix

#697 fix @import in style.css
  src/style.css
Labels: wontfix

#699 [Team-W1]: hotfix 7 items in mobile
  src/style.css
Labels: wontfix

#716 [Testimonials W1]: fix slider in ie
  src/component.js
  src/style.css
Labels: wontfix

#724 W/lucario/cover/dev
  package.json
  src/style.css
Labels: wontfix

#726 [Why-W3]: merge with prod
  block.https.weblium.co
  package.json
  src/component.js
  src/options.json
  src/style.css
Labels: good first issue

#727 [About-W3]: merge with prod
  block.https.weblium.co
  package.json
  src/component.js
  src/options.json
  src/style.css
Labels: good first issue

#733 [Header-W2]: hotfix
  package.json
  src/component.js
  src/style.css
Labels: wontfix

#729 [FAQ-W3]: merge with prod
  assets/bg.jpg
  block.https.weblium.co
  package.json
  src/component.js
  src/options.json
  src/style.css
Labels: wontfix

#788 [Cover-W3]: add optional button
  src/component.js
  src/style.css
Labels: enhancement

#793 [Cover-W3]: replace header into div
  src/component.js
Labels: wontfix

#802 W/lucario/cover/dev
  package.json
  src/style.css
Labels: wontfix

#734 [CTA-W3]: merge with prod
  block.https.weblium.co
  package.json
  src/component.js
  src/style.css
Labels: good first issue

#736 [Footer-W3]: merge to prod
  package.json
  src/component.js
  src/style.css
Labels: good first issue
